### PR TITLE
[UPD] Refacroring and review view routing

### LINKED ISSUE #11: Make app to be exceuted via cli
While runing app from cli php -S localhost:8088 the routing looks that it does not work correctly

### PR DESCRIPTION
**Pull request by bim-g**
closes #11

### CODE REVIEW

File: src/Core/Routing/Router.php [hunk 1]
```diff
@@ -8,64 +8,52 @@
 class  Router{
 
         private  $_url;
-        private  $routes=[];
-        private  $_nameRoute=[];
+        private  array $routes;
```
Comment (bim-g) [inline src/Core/Routing/Router.php:11]: data type for applicatoin variable

File: src/Core/Routing/Router.php [hunk 2]
```diff
@@ -8,64 +8,52 @@
...
 
         function __construct()
         {
-            $this->_url=$this->getMethodeUrl();
-        }
-
-        /**
-         * @return mixed|void
-         */
-        private function getMethodeUrl(){
```
Comment (bim-g) [inline src/Core/Routing/Router.php:22]: Remove uselless method

**Review by bim-g — COMMENTED** [review]
Refactoring completed

File: src/Core/Routing/Router.php (hunk 1 above)
Comment (bim-g) [reply src/Core/Routing/Router.php:11]: Good
